---
- name: playbook to install the SteamCMD cli client and CSGO server
  hosts: localhost
  tasks:
  - name: use apt to update its cache
    become: yes
    apt:
       update_cache: yes
  - name: install setfacl
    become: yes
    apt:
      update_cache: true
      package: acl
  - name: Add multiverse
    become: yes
    ansible.builtin.apt_repository:
      repo: "{{item}}"
      state: present
      update_cache: true
    with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports main restricted universe multiverse'
    - 'deb http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-security multiverse'
  - name: add software-properties-common
    become: yes
    apt:
       package: software-properties-common
       update_cache: yes
  - name: Enable i386 architecture
    become: yes
    command: /usr/bin/dpkg --add-architecture i386
  - name: use apt to update its cache
    become: yes
    apt:
       update_cache: yes
  - name: accept steam license
    become: yes
    debconf:
      name: "steam"
      question: "steam/question"
      value: "I AGREE"
      vtype: "select"
  - name: install steamcmd
    become: yes
    apt:
      update_cache: true
      package: ['ca-certificates', 'lib32gcc-s1', 'lib32stdc++6', 'libcurl4-gnutls-dev:i386', 'locales', 'steamcmd']
  - name: install various tools
    become: yes
    apt:
      update_cache: true
      package: ['btop', 'cifs-utils', 'curl', 'less', 'prometheus-node-exporter', 'vim']
  - name: Install filebeat
    # https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
    block:
      - name: install apt-transport tools
        become: yes
        apt:
          update_cache: true
          package: ['apt-transport-https']
      - name: Add elasticsearch keyring
        become: yes
        ansible.builtin.apt_key:
          url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
          keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
      - name: Add elasticsearch repo
        become: yes
        ansible.builtin.apt_repository:
          repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
          state: present
      - name: install filebeat
        become: yes
        apt:
          update_cache: true
          package: ['filebeat']
      - name: Enable filebeat service, and not touch the state
        become: yes
        ansible.builtin.service:
          name: filebeat
          enabled: yes
  - name: add steam users
    become: yes
    user:
      name: "steam"
      comment: "SteamCMD owner"
      home: "/data/steam"
      shell: "/usr/bin/bash"
  - name: allow steam user to update steamcmd
    become: yes
    ansible.builtin.file:
      path: /usr/lib/games
      group: steam
      mode: g+w
  - name: Adding ansible user to group steam
    become: yes
    user: 
      name: ansible
      groups: steam
      append: yes
  - name: Create the csgo_legacy directory
    become: yes
    become_user: steam
    ansible.builtin.file:
      path: /data/steam/csgo_legacy
      state: directory
      mode: '0755'
  - name: install git repo with the scripts for the csgo server
    become: yes
    become_user: steam
    git:
      repo: 'https://github.com/henkoch/csgo_legacy_server.git'
      dest: /data/steam/csgo_git_repo
      update: yes
      version: azure_intro
