services:
  csgo:
    image: steam_server:0.2.9
    container_name: csgo-ds
    volumes:
      - type: bind
        source: ${HOME}/Downloads/csgo_legacy
        target: /data/steam/csgo_legacy
      - type: bind
        source: ${PWD}/csgo_scripts
        target: /data/steam/csgo_git_repo/docker/csgo_scripts
    network_mode: host
    restart: unless-stopped
    command: /data/steam/csgo_git_repo/docker/csgo_scripts/run_server.sh



